name: Publish Docs to GH Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Create dist directory"
        run: mkdir dist
      - name: "Copy documentation files into root"
        run: cp -r docs/* dist/
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          allow_empty_commit: true
