name: Publish to NPM

on:
  release:
    types: [ created ]

jobs:
  publish-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Auth for npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_ORG }}" >
          ~/.npmrc

      - name: whoami
        run: npm whoami

      - name: Publish core
        run: npm publish --access=public --provenance

  loitering:
    # need to accept version from release later on
    needs: publish-core
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: Wait for core to be available on npm
        run: |
          echo "Waiting for core to be available"
          until npm view @lilac-wysiwyg/core version > /dev/null 2>&1; do
            echo "Still waiting..."
            sleep 10
          done
          echo "@lilac-wysiwyg/core is now available on npm!"

      - name: Wait 1 minute
        run: sleep 60

  publish-adapters:
    needs: loitering
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        package:
          - adapter/angular
          - adapter/react
          - adapter/svelte
          - adapter/vanilla
          - adapter/vue

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Auth for npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_ORG }}" >
          ~/.npmrc

      - name: whoami
        run: npm whoami

      - name: Publish ${{ matrix.package }}
        working-directory: ${{ matrix.package }}
        run: npm publish --access=public --no-git-checks
