name: Publish to NPM

on:
  release:
    types: [ created ]

jobs:
  publish-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Clean adapters
        run: rm -rf dist/adapter

      - name: Auth for npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_ORG }}" >
          ~/.npmrc

      - name: Publish core
        run: npm publish --access=public --provenance

  publish-adapters:
    needs: publish-core
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        package:
          - adapter/angular
          - adapter/react
          - adapter/svelte
          - adapter/vanilla
          - adapter/vue

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Wait for core to be published
        run: sleep 30

      - name: Build
        run: pnpm build

      - name: Auth for npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_ORG }}" >
          ~/.npmrc

      - name: Publish ${{ matrix.package }}
        working-directory: ${{ matrix.package }}
        run: npm publish
